TITLE_1: SEL0615
TITLE_2: Circuitos Eletrônicos II
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro AA …</li>
    <li>Artigo BB …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SEL0615-Circuitos-Eletronicos-II
HERO_FILE: circuitos-eletronicos-ii.png